name: Update Parent Checklist

on:
  issues:
    types: [closed, reopened]

permissions:
  issues: write

jobs:
  update-parent-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Update parent issue checkboxes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;
            const repo = context.repo;
            const isClosed = issue.state === 'closed';
            const isCompleted = issue.state_reason === 'completed';
            const shouldCheck = isClosed && isCompleted;
            const shouldUncheck = !shouldCheck;

            const { data: searchResults } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${repo.owner}/${repo.repo} type:issue ${issueNumber}`,
            });

            for (const parent of searchResults.items) {
              if (parent.number === issueNumber) continue;

              let body = parent.body || '';
              const checkboxChecked = new RegExp(`- \\[x\\] #${issueNumber}(.*)`, 'g');
              const checkboxUnchecked = new RegExp(`- \\[ \\] #${issueNumber}(.*)`, 'g');
              let updatedBody = body;

              if (shouldCheck) {
                updatedBody = body.replace(checkboxUnchecked, `- [x] #${issueNumber}$1`);
              } else if (shouldUncheck) {
                updatedBody = body.replace(checkboxChecked, `- [ ] #${issueNumber}$1`);
              }

              if (updatedBody !== body) {
                await github.rest.issues.update({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: parent.number,
                  body: updatedBody,
                });
                console.log(`Updated parent issue #${parent.number} (${shouldCheck ? "checked" : "unchecked"})`);
              }
            }
