name: Auto Check Sub-Issue in Parent

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  check-parent-task:
    runs-on: ubuntu-latest
    steps:
      - name: Find parent issues mentioning this one
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const closedIssue = context.payload.issue;
            const issueNumber = closedIssue.number;
            const repo = context.repo;
            const reason = closedIssue.state_reason;

            // if (reason !== 'Done') {
            // console.log(`Issue #${closedIssue.number} closed with reason: ${closedIssue.state_reason}. Skipping update.`);
            //   return;
            // }

            // Search for issues that mention this one (parent candidates)
            const { data: issues } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${repo.owner}/${repo.repo} type:issue ${issueNumber}`,
            });

            for (const issue of issues.items) {
              if (issue.number === issueNumber) continue; // skip self

              let updatedBody = issue.body;

              // Regex to find a checklist item with this issue number
              const regex = new RegExp(`- \\[ \\] #${issueNumber}(.*)`, 'g');
              updatedBody = updatedBody.replace(regex, `- [x] #${issueNumber}$1`);

              if (updatedBody !== issue.body) {
                await github.rest.issues.update({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: issue.number,
                  body: updatedBody,
                });
                console.log(`Updated parent issue #${issue.number}`);
              }
            }
